### ISSUE TITLE
Missing dependencies 

### ISSUE THREAD

**Issue by IvailoBurov** [NitroxNova/Humanizer#1] opened 2024-01-01 15:16 UTC
Fixing dependencies doesn't help.

![изображение](https://github.com/NitroxNova/Humanizer/assets/63282037/3e777ec9-fd92-4659-b62d-0700b0cf04de)

![изображение](https://github.com/NitroxNova/Humanizer/assets/63282037/7de7aa2b-0384-40c8-9f14-ab26c01dee5e)

**Comment by NitroxNova** [comment] 2024-01-01 17:39
thank you for reporting, looks like the human meshes were corrupted, i think the problem is they're not updating in the lfs, currently trying to figure all that out

**Comment by NitroxNova** [comment] 2024-01-01 18:33
i dont really understand why, but when i download the zipped project, im having the same issue as you are. however, when i use the 'git clone' through command line, all the files open correctly, so let me know if that works for you. and also, if you download the mesh .res files seperatly through the browser and move them into the project, then it works. you specifically need the generate_mesh/human.res and the gen_clothes/clothesname/mesh.res files..

**Comment by IvailoBurov** [comment] 2024-01-01 21:54
Thanks for the reply. Github cloning solves the problem. Weird indeed...

**Comment by NitroxNova** [comment] 2024-01-02 05:16
good to know, wasnt sure if i had the files cached somehow and thats why, but im guessing its something about the compression, i'll go ahead and update the readme and close this, though its not really fixed lol

**Closed by NitroxNova** 2024-01-02 05:16 UTC
